[package]
name = "node"
version = "0.1.0"
readme = "README.md"
authors = [""]
edition = "2021"

[[bin]]
name = "node"
path = "src/main.rs"

[dependencies]
structopt = { version = "0.3", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.3"