name: CI
on: [pull_request]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -W clippy::all -D warnings
  tests-linux:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
  tests-windows:
    runs-on: windows-latest
    needs: linting
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
  mark-valid:
    runs-on: ubuntu-latest
    needs: [tests-windows, tests-linux]
    permissions:
      statuses: write
      checks: write
    steps:
      - uses: actions/github-script@v6
        env:
          parameter_url: '${{ github.event.workflow_run.html_url }}'
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "my-check-name",
              status: "completed",
              // Careful, code injection can happen.
              conclusion: "${{ github.event.workflow_run.conclusion }}",
              // This is safe, not string interpolation.
              details_url: process.env.parameter_url,
              output: {
                title: "All checks passed",
                summary: "",
                text: "",
              },
            });
